### ISSUE TITLE
Synapse data and Model weights异常

### ISSUE THREAD

**Issue by zhuofalin** [Caipengzhou/BRAU-Netplusplus#1]
您提供的Synapse data and Model weights的URL有异常，我这边出现"访问遭拒"的异常。如果您看到或更新了地址，方便发我一下吗？灰常感谢。

**Comment by Caipengzhou** [comment]
我尝试了URL没有问题，可能需要梯子

**Comment by 670768312** [comment]
您好，能否私发一下数据集和权重文件？

**Comment by Caipengzhou** [comment]
权限开放了

**Comment by Caipengzhou** [comment]
权限开放了
&nbsp;








蔡鹏洲

学生

重庆理工大学/stu/计算机科学与工程学院



重庆市巴南区红光大道69号




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "670768312"; 
Date: 2024年1月4日(星期四) 下午5:05
To: "Caipengzhou/BRAU-Netplusplus"; 
Cc: "蔡鹏洲"; "Comment"; 
Subject: Re: [Caipengzhou/BRAU-Netplusplus] Synapse data and Model weights异常 (Issue #1)

&nbsp;


 
您好，能否私发一下数据集和权重文件？

**Comment by Caipengzhou** [comment]
权限开放了








蔡鹏洲

学生

重庆理工大学/stu/计算机科学与工程学院



重庆市巴南区红光大道69号




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Jan 2, 2024 02:04 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[Caipengzhou/BRAU-Netplusplus] Synapse data and Model weights异常 (Issue #1)

&nbsp;



 
您提供的Synapse data and Model weights的URL有异常，我这边出现"访问遭拒"的异常。如果您看到或更新了地址，方便发我一下吗？灰常感谢。

**Comment by zhuofalin** [comment]
嗯 可以了@您。十分感谢

**Comment by 670768312** [comment]
十分感谢！！！
