### ISSUE TITLE
Weight file does not match the model

### ISSUE THREAD

**Issue by 670768312** [Caipengzhou/BRAU-Netplusplus#2]
你好，当我配置好环境，使用你提供的预训练权重参数进行训练时，运行synapse文件中的train.py文件时，报错，报错内容如下：
---final upsample expand_first---
pretrained_path:H:\LiRongHua\BRAU_net\BRAU-Netplusplus-master\synapse_train_test\biformer_base_best.pth
_IncompatibleKeys(missing_keys=['sccsa1.channel_attention.0.weight', 'sccsa1.channel_attention.0.bias', 'sccsa1.channel_attention.2.weight', 'sccsa1.channel_attention.2.bias', 'sccsa1.spatial_attention.0.weight', 'sccsa1.spatial_attention.0.bias', 'sccsa1.spatial_attention.1.weight', 'sccsa1.spatial_attention.1.bias', 'sccsa1.spatial_attention.1.running_mean', 'sccsa1.spatial_attention.1.running_var', 'sccsa1.spatial_attention.3.weight', 'sccsa1.spatial_attention.3.bias', 'sccsa1.spatial_attention.4.weight', 'sccsa1.spatial_attention.4.bias', 'sccsa1.spatial_attention.4.running_mean', 'sccsa1.spatial_attention.4.running_var', 'sccsa2.channel_attention.0.weight', 'sccsa2.channel_attention.0.bias', 'sccsa2.channel_attention.2.weight', 'sccsa2.channel_attention.2.bias', 'sccsa2.spatial_attention.0.weight', 'sccsa2.spatial_attention.0.bias', 'sccsa2.spatial_attention.1.weight', 'sccsa2.spatial_attention.1.bias', 'sccsa2.spatial_attention.1.running_mean', 'sccsa2.spatial_attention.1.running_var', 'sccsa2.spatial_attention.3.weight', 'sccsa2.spatial_attention.3.bias', 'sccsa2.spatial_attention.4.weight', 'sccsa2.spatial_attention.4.bias', 'sccsa2.spatial_attention.4.running_mean', 'sccsa2.spatial_attention.4.running_var', 'sccsa3.channel_attention.0.weight', 'sccsa3.channel_attention.0.bias', 'sccsa3.channel_attention.2.weight', 'sccsa3.channel_attention.2.bias', 'sccsa3.spatial_attention.0.weight', 'sccsa3.spatial_attention.0.bias', 'sccsa3.spatial_attention.1.weight', 'sccsa3.spatial_attention.1.bias', 'sccsa3.spatial_attention.1.running_mean', 'sccsa3.spatial_attention.1.running_var', 'sccsa3.spatial_attention.3.weight', 'sccsa3.spatial_attention.3.bias', 'sccsa3.spatial_attention.4.weight', 'sccsa3.spatial_attention.4.bias', 'sccsa3.spatial_attention.4.running_mean', 'sccsa3.spatial_attention.4.running_var', 'layers_up.0.expand.weight', 'layers_up.0.norm.weight', 'layers_up.0.norm.bias', 'layers_up.1.blocks.0.pos_embed.weight', 'layers_up.1.blocks.0.pos_embed.bias', 'layers_up.1.blocks.0.norm1.weight', 'layers_up.1.blocks.0.norm1.bias', 'layers_up.1.blocks.0.attn.lepe.weight', 'layers_up.1.blocks.0.attn.lepe.bias', 'layers_up.1.blocks.0.attn.qkv.qkv.weight', 'layers_up.1.blocks.0.attn.qkv.qkv.bias', 'layers_up.1.blocks.0.attn.wo.weight', 'layers_up.1.blocks.0.attn.wo.bias', 'layers_up.1.blocks.0.norm2.weight', 'layers_up.1.blocks.0.norm2.bias', 'layers_up.1.blocks.0.mlp.0.weight', 'layers_up.1.blocks.0.mlp.0.bias', 'layers_up.1.blocks.0.mlp.3.weight', 'layers_up.1.blocks.0.mlp.3.bias', 'layers_up.1.blocks.1.pos_embed.weight', 'layers_up.1.blocks.1.pos_embed.bias', 'layers_up.1.blocks.1.norm1.weight', 'layers_up.1.blocks.1.norm1.bias', 'layers_up.1.blocks.1.attn.lepe.weight', 'layers_up.1.blocks.1.attn.lepe.bias', 'layers_up.1.blocks.1.attn.qkv.qkv.weight', 'layers_up.1.blocks.1.attn.qkv.qkv.bias', 'layers_up.1.blocks.1.attn.wo.weight', 'layers_up.1.blocks.1.attn.wo.bias', 'layers_up.1.blocks.1.norm2.weight', 'layers_up.1.blocks.1.norm2.bias', 'layers_up.1.blocks.1.mlp.0.weight', 'layers_up.1.blocks.1.mlp.0.bias', 'layers_up.1.blocks.1.mlp.3.weight', 'layers_up.1.blocks.1.mlp.3.bias', 'layers_up.1.blocks.2.pos_embed.weight', 'layers_up.1.blocks.2.pos_embed.bias', 'layers_up.1.blocks.2.norm1.weight', 'layers_up.1.blocks.2.norm1.bias', 'layers_up.1.blocks.2.attn.lepe.weight', 'layers_up.1.blocks.2.attn.lepe.bias', 'layers_up.1.blocks.2.attn.qkv.qkv.weight', 'layers_up.1.blocks.2.attn.qkv.qkv.bias', 'layers_up.1.blocks.2.attn.wo.weight', 'layers_up.1.blocks.2.attn.wo.bias', 'layers_up.1.blocks.2.norm2.weight', 'layers_up.1.blocks.2.norm2.bias', 'layers_up.1.blocks.2.mlp.0.weight', 'layers_up.1.blocks.2.mlp.0.bias', 'layers_up.1.blocks.2.mlp.3.weight', 'layers_up.1.blocks.2.mlp.3.bias', 'layers_up.1.blocks.3.pos_embed.weight', 'layers_up.1.blocks.3.pos_embed.bias', 'layers_up.1.blocks.3.norm1.weight', 'layers_up.1.blocks.3.norm1.bias', 'layers_up.1.blocks.3.attn.lepe.weight', 'layers_up.1.blocks.3.attn.lepe.bias', 'layers_up.1.blocks.3.attn.qkv.qkv.weight', 'layers_up.1.blocks.3.attn.qkv.qkv.bias', 'layers_up.1.blocks.3.attn.wo.weight', 'layers_up.1.blocks.3.attn.wo.bias', 'layers_up.1.blocks.3.norm2.weight', 'layers_up.1.blocks.3.norm2.bias', 'layers_up.1.blocks.3.mlp.0.weight', 'layers_up.1.blocks.3.mlp.0.bias', 'layers_up.1.blocks.3.mlp.3.weight', 'layers_up.1.blocks.3.mlp.3.bias', 'layers_up.1.blocks.4.pos_embed.weight', 'layers_up.1.blocks.4.pos_embed.bias', 'layers_up.1.blocks.4.norm1.weight', 'layers_up.1.blocks.4.norm1.bias', 'layers_up.1.blocks.4.attn.lepe.weight', 'layers_up.1.blocks.4.attn.lepe.bias', 'layers_up.1.blocks.4.attn.qkv.qkv.weight', 'layers_up.1.blocks.4.attn.qkv.qkv.bias', 'layers_up.1.blocks.4.attn.wo.weight', 'layers_up.1.blocks.4.attn.wo.bias', 'layers_up.1.blocks.4.norm2.weight', 'layers_up.1.blocks.4.norm2.bias', 'layers_up.1.blocks.4.mlp.0.weight', 'layers_up.1.blocks.4.mlp.0.bias', 'layers_up.1.blocks.4.mlp.3.weight', 'layers_up.1.blocks.4.mlp.3.bias', 'layers_up.1.blocks.5.pos_embed.weight', 'layers_up.1.blocks.5.pos_embed.bias', 'layers_up.1.blocks.5.norm1.weight', 'layers_up.1.blocks.5.norm1.bias', 'layers_up.1.blocks.5.attn.lepe.weight', 'layers_up.1.blocks.5.attn.lepe.bias', 'layers_up.1.blocks.5.attn.qkv.qkv.weight', 'layers_up.1.blocks.5.attn.qkv.qkv.bias', 'layers_up.1.blocks.5.attn.wo.weight', 'layers_up.1.blocks.5.attn.wo.bias', 'layers_up.1.blocks.5.norm2.weight', 'layers_up.1.blocks.5.norm2.bias', 'layers_up.1.blocks.5.mlp.0.weight', 'layers_up.1.blocks.5.mlp.0.bias', 'layers_up.1.blocks.5.mlp.3.weight', 'layers_up.1.blocks.5.mlp.3.bias', 'layers_up.1.blocks.6.pos_embed.weight', 'layers_up.1.blocks.6.pos_embed.bias', 'layers_up.1.blocks.6.norm1.weight', 'layers_up.1.blocks.6.norm1.bias', 'layers_up.1.blocks.6.attn.lepe.weight', 'layers_up.1.blocks.6.attn.lepe.bias', 'layers_up.1.blocks.6.attn.qkv.qkv.weight', 'layers_up.1.blocks.6.attn.qkv.qkv.bias', 'layers_up.1.blocks.6.attn.wo.weight', 'layers_up.1.blocks.6.attn.wo.bias', 'layers_up.1.blocks.6.norm2.weight', 'layers_up.1.blocks.6.norm2.bias', 'layers_up.1.blocks.6.mlp.0.weight', 'layers_up.1.blocks.6.mlp.0.bias', 'layers_up.1.blocks.6.mlp.3.weight', 'layers_up.1.blocks.6.mlp.3.bias', 'layers_up.1.blocks.7.pos_embed.weight', 'layers_up.1.blocks.7.pos_embed.bias', 'layers_up.1.blocks.7.norm1.weight', 'layers_up.1.blocks.7.norm1.bias', 'layers_up.1.blocks.7.attn.lepe.weight', 'layers_up.1.blocks.7.attn.lepe.bias', 'layers_up.1.blocks.7.attn.qkv.qkv.weight', 'layers_up.1.blocks.7.attn.qkv.qkv.bias', 'layers_up.1.blocks.7.attn.wo.weight', 'layers_up.1.blocks.7.attn.wo.bias', 'layers_up.1.blocks.7.norm2.weight', 'layers_up.1.blocks.7.norm2.bias', 'layers_up.1.blocks.7.mlp.0.weight', 'layers_up.1.blocks.7.mlp.0.bias', 'layers_up.1.blocks.7.mlp.3.weight', 'layers_up.1.blocks.7.mlp.3.bias', 'layers_up.1.upsample.expand.weight', 'layers_up.1.upsample.norm.weight', 'layers_up.1.upsample.norm.bias', 'layers_up.2.blocks.0.pos_embed.weight', 'layers_up.2.blocks.0.pos_embed.bias', 'layers_up.2.blocks.0.norm1.weight', 'layers_up.2.blocks.0.norm1.bias', 'layers_up.2.blocks.0.attn.lepe.weight', 'layers_up.2.blocks.0.attn.lepe.bias', 'layers_up.2.blocks.0.attn.qkv.qkv.weight', 'layers_up.2.blocks.0.attn.qkv.qkv.bias', 'layers_up.2.blocks.0.attn.wo.weight', 'layers_up.2.blocks.0.attn.wo.bias', 'layers_up.2.blocks.0.norm2.weight', 'layers_up.2.blocks.0.norm2.bias', 'layers_up.2.blocks.0.mlp.0.weight', 'layers_up.2.blocks.0.mlp.0.bias', 'layers_up.2.blocks.0.mlp.3.weight', 'layers_up.2.blocks.0.mlp.3.bias', 'layers_up.2.blocks.1.pos_embed.weight', 'layers_up.2.blocks.1.pos_embed.bias', 'layers_up.2.blocks.1.norm1.weight', 'layers_up.2.blocks.1.norm1.bias', 'layers_up.2.blocks.1.attn.lepe.weight', 'layers_up.2.blocks.1.attn.lepe.bias', 'layers_up.2.blocks.1.attn.qkv.qkv.weight', 'layers_up.2.blocks.1.attn.qkv.qkv.bias', 'layers_up.2.blocks.1.attn.wo.weight', 'layers_up.2.blocks.1.attn.wo.bias', 'layers_up.2.blocks.1.norm2.weight', 'layers_up.2.blocks.1.norm2.bias', 'layers_up.2.blocks.1.mlp.0.weight', 'layers_up.2.blocks.1.mlp.0.bias', 'layers_up.2.blocks.1.mlp.3.weight', 'layers_up.2.blocks.1.mlp.3.bias', 'layers_up.2.upsample.expand.weight', 'layers_up.2.upsample.norm.weight', 'layers_up.2.upsample.norm.bias', 'layers_up.3.blocks.0.pos_embed.weight', 'layers_up.3.blocks.0.pos_embed.bias', 'layers_up.3.blocks.0.norm1.weight', 'layers_up.3.blocks.0.norm1.bias', 'layers_up.3.blocks.0.attn.lepe.weight', 'layers_up.3.blocks.0.attn.lepe.bias', 'layers_up.3.blocks.0.attn.qkv.qkv.weight', 'layers_up.3.blocks.0.attn.qkv.qkv.bias', 'layers_up.3.blocks.0.attn.wo.weight', 'layers_up.3.blocks.0.attn.wo.bias', 'layers_up.3.blocks.0.norm2.weight', 'layers_up.3.blocks.0.norm2.bias', 'layers_up.3.blocks.0.mlp.0.weight', 'layers_up.3.blocks.0.mlp.0.bias', 'layers_up.3.blocks.0.mlp.3.weight', 'layers_up.3.blocks.0.mlp.3.bias', 'layers_up.3.blocks.1.pos_embed.weight', 'layers_up.3.blocks.1.pos_embed.bias', 'layers_up.3.blocks.1.norm1.weight', 'layers_up.3.blocks.1.norm1.bias', 'layers_up.3.blocks.1.attn.lepe.weight', 'layers_up.3.blocks.1.attn.lepe.bias', 'layers_up.3.blocks.1.attn.qkv.qkv.weight', 'layers_up.3.blocks.1.attn.qkv.qkv.bias', 'layers_up.3.blocks.1.attn.wo.weight', 'layers_up.3.blocks.1.attn.wo.bias', 'layers_up.3.blocks.1.norm2.weight', 'layers_up.3.blocks.1.norm2.bias', 'layers_up.3.blocks.1.mlp.0.weight', 'layers_up.3.blocks.1.mlp.0.bias', 'layers_up.3.blocks.1.mlp.3.weight', 'layers_up.3.blocks.1.mlp.3.bias', 'concat_back_dim.1.weight', 'concat_back_dim.1.bias', 'concat_back_dim.2.weight', 'concat_back_dim.2.bias', 'concat_back_dim.3.weight', 'concat_back_dim.3.bias', 'norm_up.weight', 'norm_up.bias', 'up4.expand.weight', 'up4.norm.weight', 'up4.norm.bias', 'output.weight'], unexpected_keys=['norm.weight', 'norm.bias', 'norm.running_mean', 'norm.running_var', 'norm.num_batches_tracked', 'head.weight', 'head.bias', 'stages.0.2.pos_embed.weight', 'stages.0.2.pos_embed.bias', 'stages.0.2.norm1.weight', 'stages.0.2.norm1.bias', 'stages.0.2.attn.lepe.weight', 'stages.0.2.attn.lepe.bias', 'stages.0.2.attn.qkv.qkv.weight', 'stages.0.2.attn.qkv.qkv.bias', 'stages.0.2.attn.wo.weight', 'stages.0.2.attn.wo.bias', 'stages.0.2.norm2.weight', 'stages.0.2.norm2.bias', 'stages.0.2.mlp.0.weight', 'stages.0.2.mlp.0.bias', 'stages.0.2.mlp.3.weight', 'stages.0.2.mlp.3.bias', 'stages.0.3.pos_embed.weight', 'stages.0.3.pos_embed.bias', 'stages.0.3.norm1.weight', 'stages.0.3.norm1.bias', 'stages.0.3.attn.lepe.weight', 'stages.0.3.attn.lepe.bias', 'stages.0.3.attn.qkv.qkv.weight', 'stages.0.3.attn.qkv.qkv.bias', 'stages.0.3.attn.wo.weight', 'stages.0.3.attn.wo.bias', 'stages.0.3.norm2.weight', 'stages.0.3.norm2.bias', 'stages.0.3.mlp.0.weight', 'stages.0.3.mlp.0.bias', 'stages.0.3.mlp.3.weight', 'stages.0.3.mlp.3.bias', 'stages.1.2.pos_embed.weight', 'stages.1.2.pos_embed.bias', 'stages.1.2.norm1.weight', 'stages.1.2.norm1.bias', 'stages.1.2.attn.lepe.weight', 'stages.1.2.attn.lepe.bias', 'stages.1.2.attn.qkv.qkv.weight', 'stages.1.2.attn.qkv.qkv.bias', 'stages.1.2.attn.wo.weight', 'stages.1.2.attn.wo.bias', 'stages.1.2.norm2.weight', 'stages.1.2.norm2.bias', 'stages.1.2.mlp.0.weight', 'stages.1.2.mlp.0.bias', 'stages.1.2.mlp.3.weight', 'stages.1.2.mlp.3.bias', 'stages.1.3.pos_embed.weight', 'stages.1.3.pos_embed.bias', 'stages.1.3.norm1.weight', 'stages.1.3.norm1.bias', 'stages.1.3.attn.lepe.weight', 'stages.1.3.attn.lepe.bias', 'stages.1.3.attn.qkv.qkv.weight', 'stages.1.3.attn.qkv.qkv.bias', 'stages.1.3.attn.wo.weight', 'stages.1.3.attn.wo.bias', 'stages.1.3.norm2.weight', 'stages.1.3.norm2.bias', 'stages.1.3.mlp.0.weight', 'stages.1.3.mlp.0.bias', 'stages.1.3.mlp.3.weight', 'stages.1.3.mlp.3.bias', 'stages.2.8.pos_embed.weight', 'stages.2.8.pos_embed.bias', 'stages.2.8.norm1.weight', 'stages.2.8.norm1.bias', 'stages.2.8.attn.lepe.weight', 'stages.2.8.attn.lepe.bias', 'stages.2.8.attn.qkv.qkv.weight', 'stages.2.8.attn.qkv.qkv.bias', 'stages.2.8.attn.wo.weight', 'stages.2.8.attn.wo.bias', 'stages.2.8.norm2.weight', 'stages.2.8.norm2.bias', 'stages.2.8.mlp.0.weight', 'stages.2.8.mlp.0.bias', 'stages.2.8.mlp.3.weight', 'stages.2.8.mlp.3.bias', 'stages.2.9.pos_embed.weight', 'stages.2.9.pos_embed.bias', 'stages.2.9.norm1.weight', 'stages.2.9.norm1.bias', 'stages.2.9.attn.lepe.weight', 'stages.2.9.attn.lepe.bias', 'stages.2.9.attn.qkv.qkv.weight', 'stages.2.9.attn.qkv.qkv.bias', 'stages.2.9.attn.wo.weight', 'stages.2.9.attn.wo.bias', 'stages.2.9.norm2.weight', 'stages.2.9.norm2.bias', 'stages.2.9.mlp.0.weight', 'stages.2.9.mlp.0.bias', 'stages.2.9.mlp.3.weight', 'stages.2.9.mlp.3.bias', 'stages.2.10.pos_embed.weight', 'stages.2.10.pos_embed.bias', 'stages.2.10.norm1.weight', 'stages.2.10.norm1.bias', 'stages.2.10.attn.lepe.weight', 'stages.2.10.attn.lepe.bias', 'stages.2.10.attn.qkv.qkv.weight', 'stages.2.10.attn.qkv.qkv.bias', 'stages.2.10.attn.wo.weight', 'stages.2.10.attn.wo.bias', 'stages.2.10.norm2.weight', 'stages.2.10.norm2.bias', 'stages.2.10.mlp.0.weight', 'stages.2.10.mlp.0.bias', 'stages.2.10.mlp.3.weight', 'stages.2.10.mlp.3.bias', 'stages.2.11.pos_embed.weight', 'stages.2.11.pos_embed.bias', 'stages.2.11.norm1.weight', 'stages.2.11.norm1.bias', 'stages.2.11.attn.lepe.weight', 'stages.2.11.attn.lepe.bias', 'stages.2.11.attn.qkv.qkv.weight', 'stages.2.11.attn.qkv.qkv.bias', 'stages.2.11.attn.wo.weight', 'stages.2.11.attn.wo.bias', 'stages.2.11.norm2.weight', 'stages.2.11.norm2.bias', 'stages.2.11.mlp.0.weight', 'stages.2.11.mlp.0.bias', 'stages.2.11.mlp.3.weight', 'stages.2.11.mlp.3.bias', 'stages.2.12.pos_embed.weight', 'stages.2.12.pos_embed.bias', 'stages.2.12.norm1.weight', 'stages.2.12.norm1.bias', 'stages.2.12.attn.lepe.weight', 'stages.2.12.attn.lepe.bias', 'stages.2.12.attn.qkv.qkv.weight', 'stages.2.12.attn.qkv.qkv.bias', 'stages.2.12.attn.wo.weight', 'stages.2.12.attn.wo.bias', 'stages.2.12.norm2.weight', 'stages.2.12.norm2.bias', 'stages.2.12.mlp.0.weight', 'stages.2.12.mlp.0.bias', 'stages.2.12.mlp.3.weight', 'stages.2.12.mlp.3.bias', 'stages.2.13.pos_embed.weight', 'stages.2.13.pos_embed.bias', 'stages.2.13.norm1.weight', 'stages.2.13.norm1.bias', 'stages.2.13.attn.lepe.weight', 'stages.2.13.attn.lepe.bias', 'stages.2.13.attn.qkv.qkv.weight', 'stages.2.13.attn.qkv.qkv.bias', 'stages.2.13.attn.wo.weight', 'stages.2.13.attn.wo.bias', 'stages.2.13.norm2.weight', 'stages.2.13.norm2.bias', 'stages.2.13.mlp.0.weight', 'stages.2.13.mlp.0.bias', 'stages.2.13.mlp.3.weight', 'stages.2.13.mlp.3.bias', 'stages.2.14.pos_embed.weight', 'stages.2.14.pos_embed.bias', 'stages.2.14.norm1.weight', 'stages.2.14.norm1.bias', 'stages.2.14.attn.lepe.weight', 'stages.2.14.attn.lepe.bias', 'stages.2.14.attn.qkv.qkv.weight', 'stages.2.14.attn.qkv.qkv.bias', 'stages.2.14.attn.wo.weight', 'stages.2.14.attn.wo.bias', 'stages.2.14.norm2.weight', 'stages.2.14.norm2.bias', 'stages.2.14.mlp.0.weight', 'stages.2.14.mlp.0.bias', 'stages.2.14.mlp.3.weight', 'stages.2.14.mlp.3.bias', 'stages.2.15.pos_embed.weight', 'stages.2.15.pos_embed.bias', 'stages.2.15.norm1.weight', 'stages.2.15.norm1.bias', 'stages.2.15.attn.lepe.weight', 'stages.2.15.attn.lepe.bias', 'stages.2.15.attn.qkv.qkv.weight', 'stages.2.15.attn.qkv.qkv.bias', 'stages.2.15.attn.wo.weight', 'stages.2.15.attn.wo.bias', 'stages.2.15.norm2.weight', 'stages.2.15.norm2.bias', 'stages.2.15.mlp.0.weight', 'stages.2.15.mlp.0.bias', 'stages.2.15.mlp.3.weight', 'stages.2.15.mlp.3.bias', 'stages.2.16.pos_embed.weight', 'stages.2.16.pos_embed.bias', 'stages.2.16.norm1.weight', 'stages.2.16.norm1.bias', 'stages.2.16.attn.lepe.weight', 'stages.2.16.attn.lepe.bias', 'stages.2.16.attn.qkv.qkv.weight', 'stages.2.16.attn.qkv.qkv.bias', 'stages.2.16.attn.wo.weight', 'stages.2.16.attn.wo.bias', 'stages.2.16.norm2.weight', 'stages.2.16.norm2.bias', 'stages.2.16.mlp.0.weight', 'stages.2.16.mlp.0.bias', 'stages.2.16.mlp.3.weight', 'stages.2.16.mlp.3.bias', 'stages.2.17.pos_embed.weight', 'stages.2.17.pos_embed.bias', 'stages.2.17.norm1.weight', 'stages.2.17.norm1.bias', 'stages.2.17.attn.lepe.weight', 'stages.2.17.attn.lepe.bias', 'stages.2.17.attn.qkv.qkv.weight', 'stages.2.17.attn.qkv.qkv.bias', 'stages.2.17.attn.wo.weight', 'stages.2.17.attn.wo.bias', 'stages.2.17.norm2.weight', 'stages.2.17.norm2.bias', 'stages.2.17.mlp.0.weight', 'stages.2.17.mlp.0.bias', 'stages.2.17.mlp.3.weight', 'stages.2.17.mlp.3.bias', 'stages.3.2.pos_embed.weight', 'stages.3.2.pos_embed.bias', 'stages.3.2.norm1.weight', 'stages.3.2.norm1.bias', 'stages.3.2.attn.qkv.weight', 'stages.3.2.attn.proj.weight', 'stages.3.2.attn.proj.bias', 'stages.3.2.attn.lepe.weight', 'stages.3.2.attn.lepe.bias', 'stages.3.2.norm2.weight', 'stages.3.2.norm2.bias', 'stages.3.2.mlp.0.weight', 'stages.3.2.mlp.0.bias', 'stages.3.2.mlp.3.weight', 'stages.3.2.mlp.3.bias', 'stages.3.3.pos_embed.weight', 'stages.3.3.pos_embed.bias', 'stages.3.3.norm1.weight', 'stages.3.3.norm1.bias', 'stages.3.3.attn.qkv.weight', 'stages.3.3.attn.proj.weight', 'stages.3.3.attn.proj.bias', 'stages.3.3.attn.lepe.weight', 'stages.3.3.attn.lepe.bias', 'stages.3.3.norm2.weight', 'stages.3.3.norm2.bias', 'stages.3.3.mlp.0.weight', 'stages.3.3.mlp.0.bias', 'stages.3.3.mlp.3.weight', 'stages.3.3.mlp.3.bias'])
Namespace(root_path='H:\\LiRongHua\\BRAU_net\\modelweight_data_pretrainmodel\\Synapse\\train_npz', test_path='H:\\LiRongHua\\BRAU_net\\modelweight_data_pretrainmodel\\Synapse\\test_vol_h5', dataset='Synapse', list_dir='./lists/lists_Synapse', num_classes=9, output_dir='./save_models', max_iterations=90000, max_epochs=400, batch_size=24, num_workers=8, eval_interval=20, model_name='synapse', n_gpu=1, deterministic=1, base_lr=0.05, img_size=224, z_spacing=1, seed=1234, zip=False, cache_mode='part', resume=None, accumulation_steps=None, use_checkpoint=False, amp_opt_level='O1', tag=None, eval=False, throughput=False, module=None)
The length of train set is: 2211
93 iterations per epoch. 37200 max iterations 
  0%|                                         | 0/400 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "H:\LiRongHua\BRAU_net\BRAU-Netplusplus-master\synapse_train_test\train.py", line 124, in <module>
    trainer[dataset_name](args, net, args.output_dir)
  File "H:\LiRongHua\BRAU_net\BRAU-Netplusplus-master\synapse_train_test\trainer.py", line 105, in trainer_synapse
    for i_batch, sampled_batch in enumerate(trainloader):
  File "H:\ProgramData\Anaconda3\envs\BRAU_net\lib\site-packages\torch\utils\data\dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "H:\ProgramData\Anaconda3\envs\BRAU_net\lib\site-packages\torch\utils\data\dataloader.py", line 386, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "H:\ProgramData\Anaconda3\envs\BRAU_net\lib\site-packages\torch\utils\data\dataloader.py", line 1039, in __init__
    w.start()
  File "H:\ProgramData\Anaconda3\envs\BRAU_net\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "H:\ProgramData\Anaconda3\envs\BRAU_net\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "H:\ProgramData\Anaconda3\envs\BRAU_net\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "H:\ProgramData\Anaconda3\envs\BRAU_net\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "H:\ProgramData\Anaconda3\envs\BRAU_net\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'trainer_synapse.<locals>.worker_init_fn'

Process finished with exit code 1

**Comment by Caipengzhou** [comment]
num_workers的问题，先把num_workers设置为0试一试

**Comment by Caipengzhou** [comment]
上面一些打印的是预训练权重初始化的时候一些信息，可以在bra_unet里面将print注释掉

**Comment by 670768312** [comment]
好的谢谢
