### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by SanmAIGO** [Caipengzhou/BRAU-Netplusplus#4]
Hello author, this is really a great job. May I ask if you can share the visual code in Figure 6 in the article

**Comment by Caipengzhou** [comment]
Sorry, our visualization code is disposable, but you can follow the steps below to visualize it.
1、You can use [register_forward_hook()] to easily get the routing region indices and attention matrix.
2、You can use [cv2.applyColorMap] to convert attention score map to pseudo-colored heat map.
3、You can then alpha blend the image and heatmap (i.e. alpha*image + (1-alpha)*heatmap) to get the visualization figure。
