### ISSUE TITLE
关于训练集设置的问题

### ISSUE THREAD

**Issue by yangz9527** [Caipengzhou/BRAU-Netplusplus#5]
作者大大你好 我想问一下代码里面
![035f9656017a385cd2b7632a82b7f19](https://github.com/Caipengzhou/BRAU-Netplusplus/assets/118180487/2a23f8df-6cbd-40e1-9d13-4b9ca855f80a)
关于训练集的设置 我下载ISIC2018数据集后是这样的形式 我想问问训练代码中除了使用CSV的预处理数据外 另外一个数据集参数是不是设置为训练文件的GT

**Comment by Caipengzhou** [comment]
你好，对于ISIC2018，我们将2594张图像及对应的标签进行划分训练集、验证集、测试集。
