### ISSUE TITLE
numpy问题

### ISSUE THREAD

**Issue by zhangxuan-thecastle** [Caipengzhou/BRAU-Netplusplus#6]
出现AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
但代码里没用numpy的bool这个属性啊

**Comment by Caipengzhou** [comment]
Hello, this is a Numpy version issue, Numpy deprecated np.bool in version 1.20, and you need to use bool or np.bool_ instead.

**Comment by zhangxuan-thecastle** [comment]
> 您好，这是一个 Numpy 版本问题，Numpy 在 1.20 版本中弃用了 np.bool，您需要改用 bool 或 np.bool_。


Hello author, I created the environment using your requirements. txt and encountered this issue. I have also seen your suggestion to switch to bool, but your code did not use np.bool, so it has not been resolved

**Comment by zhangxuan-thecastle** [comment]
> 您好，这是一个 Numpy 版本问题，Numpy 在 1.20 版本中弃用了 np.bool，您需要改用 bool 或 np.bool_。


Hello author, I created the environment using your requirements. txt and encountered this issue. I have also seen your suggestion to switch to bool, but your code did not use np. bool. It seems that the image library used np and bool, but the highest version of the image is 0.4.0. I cannot upgrade the image processing

**Comment by zhangxuan-thecastle** [comment]
> 您好，这是一个 Numpy 版本问题，Numpy 在 1.20 版本中弃用了 np.bool，您需要改用 bool 或 np.bool_。



Solved, thank you
